# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fista_sparse <- function(A, b, lambda, x_true, niter, backtrack, w = NULL, conv = 1e-10) {
    .Call(`_multivar_fista_sparse`, A, b, lambda, x_true, niter, backtrack, w, conv)
}

norm2 <- function(x) {
    .Call(`_multivar_norm2`, x)
}

lamloopFISTA <- function(beta_, Y, Z, W_, lambda1, eps, YMean2, ZMean2, B1, step) {
    .Call(`_multivar_lamloopFISTA`, beta_, Y, Z, W_, lambda1, eps, YMean2, ZMean2, B1, step)
}

