# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fista_sparse <- function(A, b, lambda, x_true, niter, backtrack, w = NULL, conv = 1e-10) {
    .Call(`_multivar_fista_sparse`, A, b, lambda, x_true, niter, backtrack, w, conv)
}

showValue <- function(x) {
    invisible(.Call(`_multivar_showValue`, x))
}

norm2 <- function(x) {
    .Call(`_multivar_norm2`, x)
}

ST1a <- function(z, gam) {
    .Call(`_multivar_ST1a`, z, gam)
}

ST3a <- function(z, gam) {
    .Call(`_multivar_ST3a`, z, gam)
}

ind <- function(n2, m) {
    .Call(`_multivar_ind`, n2, m)
}

FISTA <- function(Y, Z, B, W, lambda1, eps, step, stopping_crit = 0L) {
    .Call(`_multivar_FISTA`, Y, Z, B, W, lambda1, eps, step, stopping_crit)
}

lamloopFISTA <- function(beta_, Y, Z, W_, lambda1, eps, B1, step, warmstart = FALSE, stopping_crit = 0L) {
    .Call(`_multivar_lamloopFISTA`, beta_, Y, Z, W_, lambda1, eps, B1, step, warmstart, stopping_crit)
}

lamloopFISTA_offset <- function(beta_, Y, Z, W_, lambda1, eps, ZMean2, B1, step, offset, warmstart = FALSE, stopping_crit = 0L) {
    .Call(`_multivar_lamloopFISTA_offset`, beta_, Y, Z, W_, lambda1, eps, ZMean2, B1, step, offset, warmstart, stopping_crit)
}

